-- 게시판 및 댓글 테이블 생성
USE backend;

CREATE TABLE BOARD(
    BCODE INT AUTO_INCREMENT PRIMARY KEY,
    SUBJECT VARCHAR(100),
    CONTENT TEXT,
    WRITER VARCHAR(50),
    REGDATE DATE
);

CREATE TABLE REPLY(
    RCODE INT AUTO_INCREMENT PRIMARY KEY,
    BCODE INT,
    REPLY VARCHAR(200),
    WRITER VARCHAR(50),
    REGDATE DATE
);
